test: not able to view files on chpl download page when logged in
chpladmin/chpl-test pull request #100
Opened 2019-02-07 16:53 UTC by iyerashwin14

2019-02-07 17:18 UTC, andlar requested changes

2019-02-07 17:18 UTC, andlar commented on src/test/resources/Features/login.feature
> +    Then I should be logged in to CHPL as "ACB Admin"
If the idea is to test logging in as different users, the do it correctly:
```
Scenario Outline: User logs in as given ROLE
  Given I'm logged in as "<ROLE>"
  Then I should be logged in to CHPL as "<Name">
Examples
| ROLE       | Name      |
| ROLE_ADMIN | AQA Admin |
| ROLE_ONC   | AQA ONC   |
| ROLE_ACB   | AQA ACB   |
```

2019-02-07 17:18 UTC, andlar commented on src/test/resources/Features/OCD-1764-chpldownload.feature
> +    And I should be logged in to CHPL as "Admin"
This `And` step should not be here. This step is a validation step and not appropriate for this scenario

2019-02-07 17:18 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/stepDefinitions/LoginSteps.java
> +    private String adminPassword = System.getProperty("adminPassword");
All of our users are Admin in one way of another. If you're going to distinguish between them, use the ROLEs we use everywhere else. To get all three of the AQA users in this property file you should have
```
roleAdminUsername
roleAdminPassword
roleOncUsername
roleOncPassword
roleAcbUsername
roleAcbPassword

2019-02-07 17:18 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/stepDefinitions/LoginSteps.java
> +    @Given("^I'm logged in as an Admin$")
```suggestion
    @Given("^I'm logged in as an \"([^\"]*)\"$")
```

2019-02-07 17:18 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/stepDefinitions/LoginSteps.java
> +    @Given("^I'm logged in as an Admin$")
```suggestion
    @Given("^I'm logged in as "ROLE"$")
```

2019-02-07 17:18 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/stepDefinitions/LoginSteps.java
> +        LoginPage.username(driver).sendKeys(adminUsername);
Here, do a switch or if/else based on the ROLE string to figure out what username and password you should use:
```
String username;
String password
if (role.equalsIgnoreCase("ROLE_ADMIN")) {
username = roleAdminUsername
... etc.
```

2019-02-07 17:18 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/stepDefinitions/LoginSteps.java
>          assertTrue(actualString.contains("Welcome"));
This "Welcome" text should be extended to show something like "Welcome, <insert appropriate "name" variable here>"

2019-02-11 13:21 UTC, ashwinimore reviewed
We did talk about most of the suggested changes. I am ok with the PR once Andrew's comments are resolved.

2019-02-13 16:39 UTC, ashwinimore approved these changes

2019-02-13 16:49 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/stepDefinitions/LoginSteps.java
> +        }
```suggestion
        } else {
        throw new IllegalArgumentException("Incorrect role found: " + role);
        }
```
If you don't catch this here, we'd just end up waiting for the login page to load, then waiting for an empty username/password to be submitted, which probably wouldn't even work, but in any case we should do something about it

2019-02-13 16:58 UTC, andlar approved these changes

2019-02-13 16:58 UTC, merged