test: OCD-2696-test cache is re-initialized after an activity
chpladmin/chpl-test pull request #111
Opened 2019-02-25 21:55 UTC by ashwinimore

2019-02-25 22:12 UTC, andlar requested changes

2019-02-25 22:12 UTC, andlar commented on src/test/resources/Features/verifyEndpointsReturnCorrectResponse.feature
> +    When I edit ACB name and save
Reading this, it looks like, at the end of the scenario, the name has changed. I'd change this step to `I edit ACB name to be "ICSA Labs-edited" and save`, and add a step below that is `I edit ACB name to be "ICSA Labs" and save`.

That way it's clear that the name _is_ changing, but not permanently

2019-02-26 20:09 UTC, iyerashwin14 approved these changes

2019-02-27 01:21 UTC, andlar approved these changes

2019-02-27 02:12 UTC, merged