Updating login page assertion
chpladmin/chpl-test pull request #188
Opened 2019-11-21 18:49 UTC by palakpatel311

Corrected login test which was failing

2019-11-21 18:58 UTC, iyerashwin14 requested changes

2019-11-21 18:58 UTC, iyerashwin14 commented on src/test/java/gov/healthit/chpl/aqa/pageObjects/LoginPage.java
>      /**
Did you add a character 's' at the end '}' ?

2019-11-21 20:01 UTC, andlar approved these changes

2019-11-22 16:51 UTC, iyerashwin14 approved these changes

2019-11-22 19:35 UTC, merged