test: change request
chpladmin/chpl-test pull request #192
Opened 2019-12-12 12:35 UTC by iyerashwin14

2019-12-12 13:29 UTC, andlar approved these changes
Only one comment, and that one doesn't require a change, though I wouldn't mind if it were updated

2019-12-12 13:29 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/asserts/DeveloperDashboardPageAsserts.java
> +        System.out.println(actualTitle);
Debug code?

2019-12-12 14:04 UTC, ashwinimore requested changes

2019-12-12 14:04 UTC, ashwinimore commented on src/test/resources/Features/changeRequests.feature
> +Scenario: User logs in as ROLE and sees product edit link exists on new developer page
Scenario summary doesn't match what the scenario is for - test is for change request, not the product edit link

2019-12-12 14:50 UTC, iyerashwin14 commented on src/test/resources/Features/changeRequests.feature
> +Scenario: User logs in as ROLE and sees product edit link exists on new developer page
copy-paste error, will fix it :)

2019-12-18 16:56 UTC, ashwinimore approved these changes

2019-12-18 16:57 UTC, merged