OCD-1970 - Verify modification of G1/G2 values
chpladmin/chpl-test pull request #26
Opened 2018-04-20 20:25 UTC by ashwinimore

@andlar 
@brianlindsy 
@tmy1313

2018-04-21 11:22 UTC, andlar requested changes
I've only just realized. The best way to review these PRs is to start at the bottom, and go through the Feature, then the Steps, then the Page Objects. Probably best to look at comments that way too :)

Edited to add: Oh, weird! The comments are put in the review in the order I wrote them, so the comments can be read top down, even though I wrote them bottom up.

2018-04-21 11:22 UTC, andlar commented on src/test/resources/Features/OCD-1970-ModificationOfG1G2Values.feature
> +Scenario Outline: Mapping legacy values for G1
I could see this Scenario and the previous one being combined, using a "Then" step of "Measure Successfully Tested for `<gOption>` should display..."

2018-04-21 11:22 UTC, andlar commented on src/test/resources/Features/OCD-1970-ModificationOfG1G2Values.feature
> +	And When I look at  Successfully Tested G1G2 Measures
Make this a second "When-Then" set. So the whole thing would be
```Given
When
Then
When
Then
```

I wasn't sure if that was okay, but https://stackoverflow.com/questions/12060011/is-it-acceptable-to-write-a-given-when-then-when-then-test-in-gherkin says it is

2018-04-21 11:22 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/pageObjects/ListingDetailsPage.java
> +     * @return requiredText element
Should mention something in the javadoc for when "null" could be returned

2018-04-21 11:22 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/pageObjects/ListingDetailsPage.java
> +        element = driver.findElement(By.xpath("//*[@id=\"criteria_" + number + "_details_header\"]/div/table/tbody/tr[3]/td[2]"));
This will only find the right row if the Listing has the possibility of both GAP and a Standard. Do all of the G1/G2 measures have both of those? If not we should probably add an ID to the rows of the criteria details section

2018-04-23 14:28 UTC, tmy1313 submitted a review, later dismissed

2018-04-23 18:43 UTC, brianlindsy submitted a review, later dismissed

2018-04-23 18:54 UTC, ashwinimore commented on src/test/java/gov/healthit/chpl/aqa/pageObjects/ListingDetailsPage.java
> +        element = driver.findElement(By.xpath("//*[@id=\"criteria_" + number + "_details_header\"]/div/table/tbody/tr[3]/td[2]"));
Adding ids to rows is good idea. For this test, the test data i have used for existing listings works well for selected criteria in the listings.

2018-04-23 20:08 UTC, andlar approved these changes

2018-04-23 20:22 UTC, merged