OCD-1877-SED text update
chpladmin/chpl-test pull request #4
Opened 2017-11-06 17:32 UTC by ashwinimore

Review request:
@andlar 
@brianlindsy 
@kekey1

2017-11-06 18:12 UTC, andlar requested changes

2017-11-06 18:12 UTC, andlar commented on src/test/java/RESTAssuredTests/APICallsTrailingslashUpdate.java
> +}
Is this test actually running any tests?

2017-11-06 18:12 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +	public static void load_listings_details_page(WebDriver driver) {
Can this method take another parameter that is the ID of the listing? Then you could use this single method in many places, where your Feature is written as something like `Given I am on the Details page for Listing "8481"`

2017-11-06 18:12 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +			System.out.println("page title is : "+actualTitle);
These last two lines don't have anything to do with the stated reason for the method

2017-11-06 18:12 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +
The first lines here should be part of the method above where we get to the page. This method is there to "open the sed section of the accordion"; it should not be navigating anywhere.

2017-11-06 18:12 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +
The first lines here should be part of the method above where we get to the page. This method is there to "open the sed section of the accordion"; it should not be navigating anywhere.

2017-11-06 18:12 UTC, andlar commented on src/test/java/stepDefinitions/SEDTweaksSteps.java
> +		System.out.println("No. of rows: "+Rows.size());
Why print this?

2017-11-06 18:12 UTC, andlar commented on src/test/java/stepDefinitions/SEDTweaksSteps.java
>  		 //to print all the values inside the table
Why print all the rows? The method is looking for criteria title/number; what does that have to do with `System.out`-ing a lot of lines?

2017-11-06 18:12 UTC, andlar commented on src/test/resources/Features/SEDTweaks.feature
> +
This scenario should be something like:
```
Scenario: Verify usability report title update
Given I am on the listing details page for Listing "8381"
When I open the SED details accordion
Then the usability report text should read as "full usability report"
```

2017-11-06 18:57 UTC, kekey1 reviewed
Agree with Andrew's comments; I would approve after those items are addressed.

2017-11-06 21:26 UTC, kekey1 requested changes

2017-11-06 21:26 UTC, kekey1 commented on src/test/java/RESTAssuredTests/APICallsTrailingslashUpdate.java
> +		given().get("https://chpl.ahrqstg.org/rest/announcements/").then().statusCode(200).log().all();
Do you want to also test announcements without a / ? Looks like all the other calls below test both with and without /.

2017-11-06 21:29 UTC, brianlindsy commented on src/test/java/RESTAssuredTests/APICallsTrailingslashUpdate.java
> +	public void testAPIcallswithoutlashes()
I think you mean 'testAPIcallswithoutslashes()' ?

2017-11-06 21:52 UTC, kekey1 approved these changes

2017-11-06 21:53 UTC, brianlindsy approved these changes

2017-11-07 02:02 UTC, andlar approved these changes

2017-11-07 03:06 UTC, merged