OCD-1940-script to verify text after fuzzy match update
chpladmin/chpl-test pull request #5
Opened 2017-12-26 22:34 UTC by ashwinimore

Please review PR:
@andlar 
@brianlindsy 
@kekey1

2017-12-27 13:47 UTC, kekey1 approved these changes

2017-12-27 16:53 UTC, brianlindsy approved these changes

2017-12-30 12:40 UTC, andlar requested changes

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/chpldownload_page.java
> +	public static void print_page_title(WebDriver driver) {
This looks like the kind of thing that should be in some "helper" class. It's not specific to the Download page, but could be used on any page and just return the title as a String for tests to use to verify stuff

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/chpldownload_page.java
> +		System.out.println("page title is : "+actualTitle);
We shouldn't have `System.out.println` in _any_ of our real code (maybe; there are never any absolutes, including this one, but still...). It's great for debugging, but a Page Object Class should just return things

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +	public static void load_listings_details_page(WebDriver driver) {
The indentation on this Class is weird. I think we should get @kekey1 's help with setting up that checkstyle stuff and/or auto fixing as much of the rules we have in CHPL as possible

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +		// to close certification criteria accordion that's open by default
This isn't necessary, as opening any of the accordions automatically closes all of the others

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +		element = driver.findElement(By.linkText("Return to search results"));
"Return to search results" doesn't match `edit_certified_product_link`

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +		element = driver.findElement(By.xpath("//*[@id='mainContent']/div[2]/div[2]/div/div/div[3]/div[2]/div/span/span[4]/table/thead/tr/th[1]"));
I think I added an id to that table; can you check that? It would make this a simpler xpath

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +		element = driver.findElement(By.xpath("//*[@id=\"mainContent\"]/div[2]/div[2]/div/div/div[1]/div[2]/div[1]/div/div/span[2]/a"));
Similarly with these; isn't there something like a `certification_results_panel` ID somewhere we should start from?

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +		assertTrue(actualString.contains("Standard: ISO9001:2015"));
Page Objects shouldn't have any assertions

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +		assertTrue(actualString.contains("Other - WCAG 2.0"));
Page Objects shouldn't have any assertions

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +		assertTrue(actualString.contains("Section 508 of the Rehabilitation Act"));
Page Objects shouldn't have any assertions

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/listingDetails_page.java
> +		assertTrue(actualString.contains("NISTIR 7741"));
Page Objects shouldn't have any assertions

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/search_page.java
> +		assertTrue(actualString.contains("14.07.07.1221.FIA1.16.01.1.170608"));
Page Objects shouldn't have any assertions

2017-12-30 12:40 UTC, andlar commented on src/test/java/pageObjects/search_page.java
> +		assertTrue(actualString.contains("cehrt-disclosure-information"));
Page Objects shouldn't have any assertions

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/SEDTweaksSteps.java
> +	@Then("^I should see the accordions in the following order: Criteria, CQMs, SED, G1/G2, Surveillance, Additional Info$")
This test doesn't test what it says it tests. It says it's testing ordering, but it's actually testing existence of. I think the reason for the original test was to test ordering, so the logic below should probably change. It wouldn't be wrong to _also_ have a test that tests the existence of, especially as different listings will have different sets of "existing" panels

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/SEDTweaksSteps.java
> +	assertTrue(driver.getPageSource().contains("Full Usability Report"));
We want to use Page Objects to get to the items, right? So this `assert` should be something like `listingDetails_page.getSedUsabilityReportTitle().contains("Full Usability Report"));` and the Page Object should add that method (`getSedUsabilityReportTitle`) to match it

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/SEDTweaksSteps.java
> +	assertTrue(driver.getPageSource().contains("Description of Intended Users"));
Same as above

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/SEDTweaksSteps.java
> +	assertTrue(driver.getPageSource().contains("Date SED Testing was Completed"));
Same as above

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/SEDTweaksSteps.java
> +	assertTrue(driver.getPageSource().contains("Download SED Details"));
Same as above

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/SEDTweaksSteps.java
> +		assertTrue(driver.getPageSource().contains("170.315 (a)(1): Computerized Provider Order Entry (CPOE) - Medications"));
Similar to above. This should call some sort of method in the PageObject that returns an Array of criteria titles, and then assert that various criteria w/titles are in that array. And probably that some other ones aren't; both criteria the Listing doesn't attest to, and criteria _without_ the title. E.g., `assertTrue(criteriaTitles.not.contains("170.315 (a)(3)"))`; where `criteriaTitles` is defined above as something like `String [] criteriaTitles = listingDetails.getCriteriaTitles()"`

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/chpldownloadSteps.java
> +	System.out.println("user is not logged in");
This `@Given` will need to be updated once log in works; it should check to see if the user is logged in, and if it is, should figure out how to click the "Log Out" button. Probably doesn't need to be done now, but eventually

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/chpldownloadSteps.java
> +	public void user_clicks_on_download_file_box() throws Throwable {
This Step doesn't do anything. The PageObject automatically clicks on the select box, so when, in the "I should see n Items" Step below, the select box is found, it's been clicked already. This Step and the next should be refactored, and the entire test can probably we changed to something like: `Given I am on the Download Page And I am not logged in Then I should see n options`

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/chpldownloadSteps.java
> +		System.out.println("Number of download files: " +list.size());
Shouldn't this be an `assertTrue`? It's a `@Then` Step, which means it should be doing assertions, right?

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/chpldownloadSteps.java
> +		System.out.println("Number of definition files: " +definitionOptions.size());
Also needs an assertion

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/chpldownloadSteps.java
> +	public void user_checks_download_file_box() throws Throwable {
Does this do anything?

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/chpldownloadSteps.java
> +		for(int i=0;i<list.size();i++)
Needs assertion

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/disclosureurlSteps.java
> +		driver.get("https://chpl.ahrqstg.org/#/search");
Why doesn't this just go straight to the details page? This step depends on the Search page, which means it's fragile

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/disclosureurlSteps.java
> +		search_page.disclosure_url(driver);
There should be an assertion here

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/disclosureurlSteps.java
> +		driver.findElement(By.xpath("//*[@id=\"mainContent\"]/div[2]/div[1]/span/div[2]/h2"));
I think the "I look at..." paradigm isn't right; the "I look at `<a thing>`" that's written in Jira should probably be interpreted as "Build a part of the Page Object that allows the Steps to reference the `<a thing>`"

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/fuzzymatchtextSteps.java
> +	listingDetails_page.certification_criteria_g4_view_details(driver);
Similar to above wrt the "I look at `<a thing>`" paradigm

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/fuzzymatchtextSteps.java
> +	listingDetails_page.QMS_standard_text(driver);
Similar to above `assertTrue`s

2017-12-30 12:40 UTC, andlar commented on src/test/java/stepDefinitions/SEDTweaksSteps.java
> +	public void i_open_SED_accordion(String arg3) throws Throwable {
Why `arg3`? For that matter, why `arg1` and `arg2`? They should be meaningful names; for most of them I'd guess they should be something like `chplId`, though my guess (without looking) is the `arg1/arg2` will be `username/password`

2018-01-04 12:22 UTC, andlar approved these changes

2018-01-11 18:07 UTC, merged