OCD-2505-Verify Implementation Note update for certified_products end…
chpladmin/chpl-test pull request #70
Opened 2018-11-02 05:48 UTC by ashwinimore

…point

2018-11-02 12:20 UTC, andlar reviewed
I have some comments, but don't think they're required changes. If you want to address them that's great, if not consider this an approval

2018-11-02 12:20 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/pageObjects/ChplAPIPage.java
> +    public static WebElement mainContent(final WebDriver driver) {
I wonder if we could do something where we have a "BasePage" class that has this element in it, along with the navigation ones, and have all of our specific pages extend from that. Then all pages would have a reference to the main-content as well as navigation things, and we'd have the code in only one place

2018-11-02 12:20 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/stepDefinitions/ChplAPIDocumentationSteps.java
> +public class ChplAPIDocumentationSteps {
Take a look at "ChplDownloadSteps" and "ManageDevelopersAndProductsSteps" for examples of steps pages that extend the BaseSteps class. By extending BaseSteps you don't have to manage the webdriver, url, timeouts, etc.

2018-11-02 12:20 UTC, andlar commented on src/test/resources/Features/APIDocumentationUpdate.feature
> +    And I click on Certified Products endpoint link to view details
Either the "When" and "Then" steps shouldn't be parameterized, or the "And" step should. There's no way to do a second Example without changing the "And".

The "solves the feature" option would be to not parameterize either of them, while the "prepares for the future" option would be to do it for them all. If you _do_ do it for them all, I'd recommend putting an Example in that should have been successful even before the story started

2018-11-02 20:16 UTC, andlar requested changes
Love the changes. Just need to move the Page part into a BasePage class and we're set. Might add another Example to the Feature just for completeness, but that's not required.

2018-11-02 20:16 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/stepDefinitions/BaseSteps.java
> +    public static WebElement mainContent(final WebDriver driver) {
I like this, but it's in the wrong file. It should be in a new "BasePage.java" file in the pages directory, not in the steps file

2018-11-02 23:01 UTC, andlar requested changes

2018-11-02 23:01 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/pageObjects/ChplAPIPage.java
> +public final class ChplAPIPage {
```suggestion
public final class ChplAPIPage extends BasePage {
```

This class needs to extend the BasePage, then any calling step can do `ChplApiPage.mainContent` and get that element

2018-11-02 23:01 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/pageObjects/ChplAPIPage.java
> +    private static WebElement element = null;
```suggestion
```
This isn't needed

2018-11-02 23:01 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/pageObjects/ChplAPIPage.java
> +        element = driver.findElement(By.xpath("//*[@id=\"" + controller + "*\"]/li/h4/a"));
```suggestion
        return driver.findElement(By.xpath("//*[@id=\"" + controller + "*\"]/li/h4/a"));
```
Can delete the next line, and do the same changes for the other PageObject elements

2018-11-02 23:01 UTC, andlar commented on src/test/java/gov/healthit/chpl/aqa/stepDefinitions/ChplAPIDocumentationSteps.java
> +        wait.until(ExpectedConditions.visibilityOf(BasePage.mainContent(getDriver())));
```suggestion
        wait.until(ExpectedConditions.visibilityOf(ChplAPIPage.mainContent(getDriver())));
```
With ChplApiPage extending BasePage, you can treat the ChplApiPage as having all of the BasePage content

2018-11-07 16:45 UTC, andlar approved these changes

2018-11-07 17:19 UTC, kekey1 approved these changes

2018-11-07 17:30 UTC, merged